### ISSUE TITLE
"Tried to set rating on a submission without an owner"

### ISSUE THREAD

**Issue by hyena** [Weasyl/weasyl#103]
Or whatever the bug is. Happens when submitting content. This is annoying and error messages that we're trained to ignore are broken windows. Let's fix it.

**Comment by charmander** [comment]
(Note to readers: this is a logged warning due to ORM misuse, not a user-visible error.)

**Comment by hyena** [comment]
Almost certainly it's these lines:

https://github.com/Weasyl/weasyl/blob/3bcf76d9325b103680875c4fbcd048476a889e12/weasyl/controllers/content.py#L56

This is one of several places where we're constructing a _partial_ orm object to treat it essentially as a struct. The various Submission `create_*()` class methods have a bit of a strange method signature that takes in partially filled submission objects.

**Comment by charmander** [comment]
Although we haven’t gotten rid of the partial-mapped-object misuse just yet, the rating check logic has been moved out of the ORM, solving this warning.
