### ISSUE TITLE
Setting for 'prevent guests from seeing my submissions'

### ISSUE THREAD

**Issue by hyena** [Weasyl/weasyl#112]
As requested by https://www.weasyl.com/journal/109611/will-stop-posting-to-weasyl

Guests can currently see all general submissions. Some people would like to prevent this for their submissions because it permits them to be indexed by search engines (which in turn may permit them to be stolen more easily).

Doing this requires a number of things:
* Adding a new per-account setting
* Blocking submission detail pages accordingly
* Blocking listing such submissions/journals/characters from showing up in all lists, folder previews, etc.

The first two items are easy. The third is fairly obnoxious.

**Comment by hyena** [comment]
While appreciating the strong feelings people have around this, philosophically it's unclear to me that this is a good idea as it impairs discovery. It's unclear to me that the lack of it facilitates art theft or how I'd go about making that claim falsifiable.

**Comment by weykent** [comment]
Quoting myself from gitter earlier:

>tbqh i think we should be letting indexers like google on any non-private content on the site

That is, allow scrapers to view non-General submissions. There's a few easy ways to implement this so it doesn't function as a trivial age-block bypass.

**Comment by hyena** [comment]
Does anyone from moderation, e.g. @hendikins, have anecdotal data on how art theft works in practice?

**Comment by weykent** [comment]
@hyena will do.

**Comment by hyena** [comment]
Closing as won't fix. At least until our feelings around this shift.
