### ISSUE TITLE
Admin/manageuser improvement: Show last known IP addresses for user

### ISSUE THREAD

**Issue by Hendikins** [Weasyl/weasyl#129]
(Originally filed as Redmine issue 139 by @skylerbunny)

Show last known IP addresses for user. This would be capped by count or number of days (say, 10 and 30 respectively).

**Comment by kfkitsune** [comment]
Resolved in #328, for the most part. Currently displays user sessions and the associated IPs. We don't currently drop the IP after N-days in the session information, but we can consider that in the future.
