### ISSUE TITLE
The State of Account Verification on Weasyl

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [Weasyl/weasyl#1368]
I'm sorry to complain about this, but why can't Weasyl rely on getting a verification email like any other site does in order to verify an account? Because if the website gets abandoned through one reason or another, the site will become virtually unusable at best.

I sadly cannot request other users to click the "vouch" button, because I am blocked off from making comments or messages to people. I hope you understand where I am getting at.

**Comment by charmander** [comment]
> I'm sorry to complain about this, but why can't Weasyl rely on getting a verification email like any other site does in order to verify an account?

spam can get really bad without it

> Because if the website gets abandoned through one reason or another, the site will become virtually unusable at best.

people probably won’t want to use an abandoned website anyway!

> I sadly cannot request other users to click the "vouch" button, because I am blocked off from making comments or messages to people.

the idea is to ask on other websites where people already know you

**Comment by ToxicHolyGrenade** [comment]
@charmander I mean, I'm not talking about the site being abandoned in the sense of the userbase, I am talking about the site's means of service. Once the service ends, the site will become inaccessible to have an account on. That's why it is a major concern. Not just for me, but for others who want to use the site as an alternative to DeviantArt.

On the subject of spamming, we would rather just keep looking for more ideal methods in order to deal with this problem, rather than the use of a vouching system, or even the bots like what Google and DeviantArt heavily relies on.

**Comment by charmander** [comment]
There are no plans to discontinue service, and the site doesn’t continue functioning without service anyway. Until we have a better solution, we’ll keep this system in place. The majority of signups so far are already vouched for by people they know instead of staff, and hopefully that only gets easier with time as more people have an account.
