### ISSUE TITLE
Community tagging - Tag addition blacklist (per-user)

### ISSUE THREAD

**Issue by Hendikins** [Weasyl/weasyl#142]
Per discussion in -directors

Same as #140, on a per-user basis.

Additional restrictions:
- Minimum of 2 non-wildcard characters in any entry
- Restrict or disallow pasting lists of tags to block

Rationale:
These restrictions should make it impractical to use this feature to completely block community tagging, but not interfere with the intended use of the tool.

**Comment by charmander** [comment]
> Restrict or disallow pasting lists of tags to block

This is trivial to work around and will just annoy people.
