### ISSUE TITLE
Moderator tools should use UTC for everything

### ISSUE THREAD

**Issue by hyena** [Weasyl/weasyl#145]
To reduce ambiguity I suggest that moderator tools should use UTC for all date/time, including both the display in logs and the interpretation of dates entered by a moderator. This way all moderators would see the same thing for e.g. a user's DOB.

This should probably be considered to be blocked on #96 to avoid merge conflicts.

**Comment by Hendikins** [comment]
Thumbs up from mod directors.

**Comment by charmander** [comment]
Every time stamp now includes a time zone (#1221), birth dates are plain dates like they should be (on the frontend, anyway), and filters (account search ) are UTC.
