### ISSUE TITLE
Improve tag blocking UI

### ISSUE THREAD

**Issue by charmander** [Weasyl/weasyl#1453]
- separate forms for adding and removing, because Rating to Filter only applies to adding – either put a Remove button next to every entry, or use checkboxes (a `<table>` is probably a good idea either way)
- remove outdated advice and labelling about blacklist filters (we used to also have whitelist filters); just call the entire feature “blocked tags”
- figure out what should happen when someone tries to add a duplicate tag (currently nothing, regardless of associated ratings); should the control to update a blocked tag’s rating bound be part of the table (radio buttons, dropdowns)?
- remove cancel button
- allow adding multiple tags at once?

**Comment by huntertur** [comment]
Does this just apply to `/manage/tagfilters`, or does the scope include additional pages?

**Comment by charmander** [comment]
@huntertur Just `/manage/tagfilters`.
