### ISSUE TITLE
Remove Impersonate User feature

### ISSUE THREAD

**Issue by ikanimew** [Weasyl/weasyl#158]
Impersonate User was originally created for finding bugs, and is honestly no longer needed. Any mod function that would need Impersonate should just have a control in the Mod, Admin or Director panels, and we can approach those as they come up.

I believe there was originally discussion about moving this feature to the new Director panel, but we can just remove it entirely.

**Comment by ikanimew** [comment]
Adding that #147 does block this.

**Comment by hyena** [comment]
Pushed in #159.
