### ISSUE TITLE
Signup recaptcha is Google and therefore locks out mainland China

### ISSUE THREAD

**Issue by skylerbunny** [Weasyl/weasyl#16]
https://www.google.com/recaptcha/ works great for signup in general, though it has been pointed out by https://twitter.com/kakurady via https://twitter.com/kakurady/status/736611710237302785 : Reminder: Chinese (individuals) can't sign up for @Weasyl ... because China blocks ReCaptcha, a Google service.

https://github.com/google/recaptcha itself is a Github project, and there was a PR that may work around this problem proposed, which was retracted and forked instead to here. https://github.com/paragonie-scott/recaptcha/commits/master (see https://github.com/paragonie-scott/recaptcha/commit/0be1113c54aceec79c5fde2c4eb44d54f0352d3e )

**Comment by strain-113** [comment]
Looking at the PR: It's basically there to let the curl request be pointed at another IP, e.g. a Tor node, so it's not a complete out of the box solution.

I think that maintaining a hole through the GFW is beyond the scope of this project and belongs at the user level (e.g. using a VPN at registration time). Non-ideal, I know, but this seems a lot of complexity on top of something that is mostly working well.

Closing as won't fix.
