### ISSUE TITLE
cdn. should redirect back to www. more often

### ISSUE THREAD

**Issue by weykent** [Weasyl/weasyl#163]
This is an nginx configuration issue, not a code issue.

An intentional feature is that by removing the filename of https://cdn.weasyl.com/~shennanigma/submissions/1306872/141137de910c21d9e7fef037cdc93110752900fab3523c7dbdf3c925a3e8bcb6/shennanigma-wiggle-baby.png you get the submission page: https://cdn.weasyl.com/~shennanigma/submissions/1306872/141137de910c21d9e7fef037cdc93110752900fab3523c7dbdf3c925a3e8bcb6/. But since `cdn.` has different cookies from `www.`, that page will not be shown as logged in. https://www.weasyl.com/~shennanigma/submissions/1306872/141137de910c21d9e7fef037cdc93110752900fab3523c7dbdf3c925a3e8bcb6/ shows the expected page, but requires manual modification from `cdn.` to `www.`. A 302 redirect should be issued from `cdn.` to `www.`.

**Comment by charmander** [comment]
This was fixed at some point!
