### ISSUE TITLE
gdoc preview a better way to embed google docs

### ISSUE THREAD

**Issue by personal-assembly-required** [Weasyl/weasyl#165]
example Google url:
https://docs.google.com/document/d/[1]/d/[2]/[3]

1: drive-service-it-comes-from(ussaly docs can some times not be here)
2: google-drive-file-ID
3.by taking off what ever is after the google file id(edit/view/suggest/other crap) and adding "htmlembed" it force Google to serve you a much more reader friendly version which will help add to the niceness of the site when viewing 

*note while I'm not the best at python id be happy to do the code to make this happen if some one can point me at where it is in the blob and then wants to submit it

**Comment by charmander** [comment]
Addressed by #1107, slightly differently.
