### ISSUE TITLE
Add a style guide

### ISSUE THREAD

**Issue by strain-113** [Weasyl/weasyl#17]
Also one for libweasyl. In addition to the syntax and docstrings, emphasize that changes should update CHANGELOG.md and include unit tests.

**Comment by charmander** [comment]
It’s usually up to maintainers to maintain the changelog. I think the same applies here.

**Comment by strain-113** [comment]
That's fair.

**Comment by strain-113** [comment]
Added by @charmander on the wiki:

https://github.com/Weasyl/weasyl/wiki/Style-guide
