### ISSUE TITLE
Get `alembic revision --autogenerate` back to empty

### ISSUE THREAD

**Issue by hyena** [Weasyl/weasyl#194]
Our models in libweasyl should reflect the reality of what's in the database. Currently this is not the case, a situation which makes it easier to accidentally corrupt the database and harder to safely write migrations.

Fix up our models so that `alembic revision --autogenerate` produces a no-op migration. This will require carefully looking at the current output, much of which is indices, etc.

For future reference the preferred way to generate revisions in weasyl is to update the model first, run `alembic revision --autogenerate`, and then fix the generated revision (e.g. transferring or converting data, etc.)

**Comment by charmander** [comment]
All databases and exports should match the migrations now!
