### ISSUE TITLE
New e-mail address isn’t verified after change

### ISSUE THREAD

**Issue by charmander** [Weasyl/weasyl#220]

**Comment by hyena** [comment]
Hm. What's the appropriate behavior for this one? Particularly if they don't click the link?

**Comment by skylerbunny** [comment]
I think the usual behavior is 'not to change the email address and drop the request'. Emails to confirm a security change usually have a time limit, like 24 or 48 hours, 'after which the link doesn't work anymore'.

**Comment by skylerbunny** [comment]
...so programatically, changing the email address first puts the change into a 'pending' state with an email sent out, and then either goes 'expired' or 'confirmed' based on either outcome.

**Comment by kfkitsune** [comment]
Fixed as part of merged PR #225 as commit https://github.com/Weasyl/weasyl/commit/8787394caabc557a55d579e0210ec4866720c773
