### ISSUE TITLE
define.get_int() may not function as expected

### ISSUE THREAD

**Issue by kfkitsune** [Weasyl/weasyl#227]
I can't tell if this function was designed this way for a reason, but it feels like a bug to me. I'm hunting down some other errors elsewhere, and I came across this... and it looked peculiar.

As it currently reads, the code does not properly return an ``int``. As an example, I would expect the following from a function returning an int:
```
>>> print(int(123.2))
123
>>>
```

Stripping all non-numerals may not match what one may expect.

```
>>> import numbers
>>> def get_int(target):
...     if isinstance(target, numbers.Number):
...             return int(target)
...     try:
...             return int("".join(i for i in target if i.isdigit()))
...     except:
...             return 0
...
>>> get_int('123.234')  # Technically a float, but the result is way incorrect from a rounded 123
123234
>>> get_int('123aaaaaaa2234')  # This isn't an int at all
1232234
>>>
```

If the intent is to perform input validation of user-input claimed integers, then the following might be preferred:

```
>>> def really_get_int(qwe):
...     try:
...             return int(qwe)
...     except ValueError:
...             return 0
...
>>> really_get_int(123)  # Really an integer
123
>>> really_get_int(123.25)  # Really a float
123
>>> really_get_int(u'123')  # Really a string
123
>>> really_get_int(u'123.25')  # Really a string
0
>>> really_get_int(u"' or 1=1")  # Not valid at all
0
>>>
```

For the last case where it converts to zero, the ``except`` case could be converted to ``int(float(qwe))`` instead of a raw ``int()``:
```
>>> print(int(float(u'123.25')))
123
```

Thoughts?

**Comment by kfkitsune** [comment]
Pending fix in upcoming branch.

**Comment by charmander** [comment]
It’s a bad function. Consider it deprecated. Not going to change its behaviour in case it breaks something, though.
