### ISSUE TITLE
Make Weasyl libssl-1.1.x compatible

### ISSUE THREAD

**Issue by skylerbunny** [Weasyl/weasyl#264]
https://packages.debian.org/stretch/libssl1.0-dev

"This is a transition package that will go away after the stretch release to provide the 1.0.X APIs for those packages that are not ready for the 1.1 version yet."

The workaround for newer Linux releases (for now) is to use this backwards-compatibility package, but we need to update our library dependencies to handle/expect libssl 1.1.

==> default:     generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
==> default:     building '_openssl' extension
==> default:     creating build/temp.linux-x86_64-2.7/build
==> default:     creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
==> default:     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
==> default:     build/temp.linux-x86_64-2.7/_openssl.c:805:23: error: conflicting types for ‘ASN1_TIME_to_generalizedtime’

(And so on)

**Comment by charmander** [comment]
Was this handled by #263?

**Comment by skylerbunny** [comment]
Resolved by #263.
