### ISSUE TITLE
Improper CSS styling on user link

### ISSUE THREAD

**Issue by skylerbunny** [Weasyl/weasyl#27]
Reported by https://twitter.com/Dragonheadthing:

![chqnwx8u4aax6zw](https://cloud.githubusercontent.com/assets/6234406/15729543/1ae626ea-281a-11e6-80cf-d255c817e3f2.jpg)

https://twitter.com/Dragonheadthing/status/726248714482778112

"When viewing an image, the top name is easily selected, but the name under the image drags.."

The problem was replied to and described thusly:

https://twitter.com/WeasylDev/status/726254694918676480

"[The issue] is just caused by improper CSS styling (the link has display:block)"

**Comment by charmander** [comment]
It’s not “improper” CSS styling, note. Being able to click anywhere in that area and activate the link was its intended effect.

I wish other browsers had a modifier key like Firefox’s (Alt) to force selection.

**Comment by weykent** [comment]
So, not a bug?
