### ISSUE TITLE
Implement OGP so Telegram et al provide rich page previews

### ISSUE THREAD

**Issue by philpem** [Weasyl/weasyl#326]
Telegram can generate previews of links when they're posted to a group chat. Some other apps (whatsapp and so on) can do this too. It's based on the OGP protocol: www.ogp.me

Several other sites already implement this - and although it's a bit of fence-painting, it'd be nice for us to have it too.

**Comment by Syfaro** [comment]
It looks like something pretty similar exists for Twitter specifically with the [`twitter_card`](https://github.com/Weasyl/weasyl/blob/00382e5d8ff60021479da51366813f6956c6212c/weasyl/submission.py#L673) methods.

For Telegram specifically, it might be worth looking into getting an [Instant View](https://instantview.telegram.org/contest).
