### ISSUE TITLE
Merge libweasyl git repository

### ISSUE THREAD

**Issue by strain-113** [Weasyl/weasyl#39]
libweasyl has been a separate project historically to help with the transition in code styles, etc. as well as to support weasyl3. These considerations are less relevant today however:
 * We're standarizing the codestyle (thanks @charmander and others for the grunt work of fixing 2 space tabs, etc.)
 * weasyl3 isn't exactly abandoned, but our approach is likely to look more incremental going forward.
At the same time juggling two different git projects is complicating code reviews, deployments, etc. Maybe it's time to put the libweasyl code in a libweasyl subdirectory in the weasyl repo. It would also make vagrant provisioning slightly more straightforward and let us use one set of standard logic for tests, coverage, flake8, etc.

n.b. that even if the libweasyl code moves into a sub-directory, it should remain its own python library separate from weasyl itself. Having the data model logic, etc. separate has been helpful for writing things like one off scripts.

**Comment by weykent** [comment]
Highly in favor. A subtree merge can consolidate the two in such a way that they can be separated out again if necessary. Having >1 repo is a band-aid attempt at solving the sucking chest wound of python packaging and overall tooling, and in practice, it ends up with a net increase of pain.

The only caveat here is that pip will _not_ install from a subdirectory, so it means that there will be no equivalent of `pip install git+https://github.com/Weasyl/libweasyl` anymore. That might not be a big deal, though.
