### ISSUE TITLE
Bring character and journal tags up to par with submissions

### ISSUE THREAD

**Issue by weykent** [Weasyl/weasyl#44]
Update the schema to allow storing tag history for journals and characters
This is a dependency of #11

**Comment by weykent** [comment]
Or maybe hopefully instead finally realize the plan to collapse them all into submissions?

**Comment by strain-113** [comment]
@weykent Can you change the title of this so it isn't the same as #11? Or close as a duplicate and make comments there.

**Comment by weykent** [comment]
Oops, yes, turns out this was filed on both weasyl and libweasyl. I moved the issue over without seeing the dupe.
