### ISSUE TITLE
Use docker for development/deployment

### ISSUE THREAD

**Issue by weykent** [Weasyl/weasyl#49]
[Docker](https://www.docker.com/), for all of its pitfalls and hype, might actually fit our use case really well, especially with travis-ci. Travis can build the docker image for the site, and that image can be used for running tests, or development, or production. The web server is nicely self-contained, aside from needing to access the filesystem. Its service dependencies are trivially spun up with `docker compose`.

Developers can also build local images and run those. It's probably even possible to keep the startup time of the development web server as fast as it is already.

This would supersede our current use of Vagrant.

Rollout steps:
- [ ] Docker first pass (#60)
- [ ] Get it running on Windows
- [ ] Use data volumes to keep track of alembic downgraders
- [ ] Build/export docs and assets using Docker.

**Comment by hyena** [comment]
@skylerbunny Any steps you want to add to this for deployment in prod?

**Comment by charmander** [comment]
Done in #1046.
