### ISSUE TITLE
Create links to the Weasyl open source project on mainsite

### ISSUE THREAD

**Issue by skylerbunny** [Weasyl/weasyl#59]
When the current news post is replaced by another, there isn't really anything specific which indicates that Weasyl is an open source project (where it is hosted, or where one can contribute).

https://twitter.com/Half_Shot says: 'Ty, @weasyl should be more proud of it and link it somewhere near the bottom :3'

I can see the case for this. Perhaps changing the page footer

Copyright © 2012–2016 Weasyl LLC

to

Weasyl, copyright © 2012–2016 Weasyl LLC, [an open source project]

and/or adding a link to the Github project under 'About' or 'Community' links on the front page?

**Comment by strain-113** [comment]
If we do this, be sure to ping back to Half_Shot so they know they were heard.

**Comment by Syfaro** [comment]
A slight variation on the footer content, why not reuse the existing current sha? Site source is a link to the GitHub repo, the hash links directly to the commit on GitHub. Not sure if 'Site source' is the best wording, but can easily be changed. 

![](http://i.imgur.com/TUhr5Mq.png)

**Comment by weykent** [comment]
It could be a little github icon or just `GitHub`. But wow yes at making the footer sha link to github directly.

**Comment by Syfaro** [comment]
Something like this then? 

![](http://i.imgur.com/GOd4lbH.png)

**Comment by charmander** [comment]
Yep, that looks great!

**Comment by charmander** [comment]
Fixed by #61. Thanks, @Syfaro!
