### ISSUE TITLE
Some thumbnail don't show

### ISSUE THREAD

**Issue by k79e** [Weasyl/weasyl#656]
e.g https://www.weasyl.com/submissions/vanttalon
https://cdn.weasyl.com/static/media/b3/1d/56/b31d56fa5ebb1f63c2d3de83b29564e48088ff4770f8662b7a2aa4e249bc342f.png

https://www.weasyl.com/~phialeofmystery/submissions/1790831/shoot-to-thrill
On this page the pic don't even show!! It's all 404

Is it same for you other guys?

**Comment by charmander** [comment]
Yes, a lot of Weasyl servers are down right now. Half the files come from one of them, so they’re temporarily missing. Unfortunately, devs can’t do anything about it.

**Comment by charmander** [comment]
Mostly fixed now. (There are still some missing files, but they’re missing for a different reason, and instead of affecting more than half of the submissions on the site it’s just tens of them.)
