### ISSUE TITLE
Please add a switch to enable/disable lazyload

### ISSUE THREAD

**Issue by k79e** [Weasyl/weasyl#657]
This lazyload is very lazy that make user experience very not smooth.
It's better to add a switch go give user more control.

https://github.com/Weasyl/weasyl/issues/639

**Comment by charmander** [comment]
I’d rather not add more switches, but we should be able to change to [native lazy-loading][1] soon.


[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1542784
