### ISSUE TITLE
403 error upon sign up

### ISSUE THREAD

**Issue by superstapes** [Weasyl/weasyl#685]
For the past month or so there has been a 403 error upon sign up at weasyl.com. Nothing comes up in search results about it
![image](https://user-images.githubusercontent.com/59581204/71846651-f190cd00-307f-11ea-83f4-79b8f7903724.png)

**Comment by charmander** [comment]
Nobody can sign up for now (https://status.weasyl.com/). We hope to put up an alternative at least soon.

**Comment by charmander** [comment]
Restored signups, with limited ability to interact until approval, in #722.
