### ISSUE TITLE
Fix narrow thanks page columns

### ISSUE THREAD

**Issue by iErrored** [Weasyl/weasyl#72]
The columns on the [awesome people/thanks page](https://www.weasyl.com/thanks) appear to be very narrow/squished, making them harder to read.

Turning off the css rule `@media (min-width: 30em){.donator-list>li{width:30%}` seems to fix the issues on Chrome (Version 51.0.2704.84 m) and Firefox (46.0.1) on my end, but I'm not too sure what exactly the rule is used for, so it may affect something else or cause weird behaviour by removing it.

**Comment by charmander** [comment]
Fixed by #91.
