### ISSUE TITLE
Allow users to change their own usernames, with restrictions

### ISSUE THREAD

**Issue by charmander** [Weasyl/weasyl#737]
- At most once per month
- At most one reserved historical username

Don’t forget `plaintext()[:_USERNAME]`.

**Comment by kfkitsune** [comment]
A question I had... how does ``weasyl/useralias.py`` factor into this? Users with ``d.get_premium()`` as ``true`` get three usernames? Current username, old username, alias? Or are we collapsing the alias mechanism into this?

Either way, it's something to keep in mind.

**Comment by charmander** [comment]
@kfkitsune Yep, three usernames. But this will still use the `useralias` table, I think.
