### ISSUE TITLE
Possible to reduce size of pngs

### ISSUE THREAD

**Issue by Jakeukalane** [Weasyl/weasyl#759]
The png images are not optimized. I used optipng and reduced from 122 Kb to 110 Kb (/assets/img). Just a suggestion if you didn't know about png optimization. Also with exiftool 38 images have been reduced in metadata (metadata could be sometimes useful though).

Feel free to mark invalid, just wanted to tell whoever leads weasyl about this and that I love your project.

**Comment by charmander** [comment]
This is true! We’re working on a migration from ImageMagick to Pillow right now (#688), which helps with metadata and compression. Once that’s done, we can check again how much better an extra PNG optimization step will make things.

**Comment by charmander** [comment]
Oh, the assets! Yes. :D
