### ISSUE TITLE
Provisioning fails due to missing gulp-autoprefixer

### ISSUE THREAD

**Issue by kfkitsune** [Weasyl/weasyl#76]
When synced with the current master https://github.com/Weasyl/weasyl/commit/98d0fe8f7aac6d5e9915e593f6c4274f8e0bafb7, building the virtual Weasyl development environment fails.

Output of...
``make setup-vagrant``: https://paste.weasyldev.com/show/1cfNfngydXyCNIq5jXyU/
``make guest-run``: https://paste.weasyldev.com/show/0DyJuVJqmtrHKPLddzWy/

In order to fix this issue and get ``make guest-run`` to work, I had to do the following:

1. ``vagrant ssh``
2. ``cd weasyl``
3. ``npm install --save-dev gulp-autoprefixer`` -- https://www.npmjs.com/package/gulp-autoprefixer
4. ``npm rebuild node-sass`` -- https://github.com/sass/node-sass/issues/1387

After the above, exiting ``vagrant ssh`` and then issuing ``make guest-run`` works as expected.

**Comment by charmander** [comment]
If gulp-autoprefixer was missing, `npm install` probably failed at some earlier point; [it’s in the dependencies][1].

Try removing `node_modules` and running `make guest-run` as usual.

  [1]: https://github.com/Weasyl/weasyl/blob/d5e9f2a99df2b8978dc06a4e0fb9f7450cf6d080/package.json#L4

**Comment by kfkitsune** [comment]
Okay, I have no idea how ``npm install`` failed there, but after ``vagrant destroy``ing, and then redoing ``vagrant up``/``make guest-run``, it finally succeeded as expected.
