### ISSUE TITLE
Show tags on results from /api/messages/submissions

### ISSUE THREAD

**Issue by taedixon** [Weasyl/weasyl#86]
[API documentation](https://projects.weasyl.com/weasylapi/#get--api-messages-submissions) indicates this route returns a list of Submission objects, which should include tags. However, no tags are actually returned. Either tags should be added to the response, or the API documentation should be updated to reflect the actual behaviour (preferably the former).

**Comment by seanmcelroy** [comment]
I strongly recommend that tags be added!  For clients that use this who would like to build in filtering, it saves many repetitive calls to get those tags for search results
