### ISSUE TITLE
Synchronize test environment DB with Alembic revisions

### ISSUE THREAD

**Issue by kfkitsune** [Weasyl/weasyl#90]
The current contents of `https://deploy.weasyldev.com/weasyl-latest-staff.sql.gz` are out of sync with the latest alembic head. The tables to be purged as a part of #68 are missing from the DB backup, and as such if an individual wanted to attempt to bring the alembic into sync with the schema, the `alembic upgrade head` would fail, due to the tables no longer existing.

Per Charmander, updating the SQL file is preferable as opposed to trying to catch/handle the tables not existing in the Alembic upgrader script (I'd agree with this).

**Comment by weykent** [comment]
Are you sure? From the latest dump (`ETag: "574a16f0-c075d"`, `Last-Modified: Sat, 28 May 2016 22:08:48 GMT`), I'm not having any problems running `alembic upgrade head`.

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade abac1922735d -> 9afc9a45510c, Add submission_tags for fast searching
INFO  [alembic.runtime.migration] Running upgrade 9afc9a45510c -> d0bffaa55b06, Index favorites by unixtime
INFO  [alembic.runtime.migration] Running upgrade d0bffaa55b06 -> 48ab4dc5599f, Do not index favorites by unixtime
INFO  [alembic.runtime.migration] Running upgrade 48ab4dc5599f -> c8c088918278, Index media by sha256
```

**Comment by kfkitsune** [comment]
The missing tables from the dump still haven't been removed from the Alembic upgrade path, though. I don't have the log, but I think Charmander mentioned that the empty tables were simply excluded from the SQL dump, since they are unused. The ``alembic upgrade head`` process works as expected, but if you were to try and, for instance, update the schema to remove the outdated tables in #68, which Charmander stated he has taken, attempting to generate an Alembic revision to drop the tables will fail in the test environment, as the tables don't exist.

See #89 for what I tried to do. In order to get the upgrade() branch of my revision to run I had to manually check if the table existed before dropping it.

**Comment by weykent** [comment]
@charmander can you clarify if you remember this conversation?

It's not clear if this is talking about the tarball or something else, because it sounds like you're saying "it's a problem with the schema in the tarball, except the tarball doesn't include these problem tables, but there's still a problem".

**Comment by charmander** [comment]
@weykent You mean the gzipped SQL file? The problem is that it doesn’t create all the tables that are in `libweasyl.models.tables`, so the database revision it claims to contain and its schema are different. It’s just a small oversight\* in the export script, and easily fixed.

**Comment by weykent** [comment]
Oh, so this isn't a problem _now_ but might be when future migrations are added.

**Comment by charmander** [comment]
This has been fixed.
