### ISSUE TITLE
Block registrations using specified e-mail providers

### ISSUE THREAD

**Issue by Hendikins** [Weasyl/weasyl#99]
This is largely aimed at disposable providers (Mailinator et al.), which have been a sustained source of spamming accounts with little to no legitimate user traffic. However, we could in future have reason to block other providers as well.

Whether the user is notified or the registration silently dropped is up for discussion.

The policy to block registrations from disposable providers was discussed and set by the directors on July 8th.

**Comment by weykent** [comment]
Is the discussion recorded somewhere?

**Comment by ikanimew** [comment]
Well it's recorded in -directors, sure. There were no objections from any directors on it.

**Comment by weykent** [comment]
@ikanimew: As written, this isn't actionable or very specific, so I was hoping the logs might be posted to elucidate the matter.
